#!/bin/bash

target=/app/easyepg
source=/config/backup
logpath=/config/logs
touch $logpath/juggler.log

if [ "$(ls -A $source)" ]; then #notEmpty
   case $1 in
      1)
         if [ -f ${source}/easyepg_backup.ver1 ]; then
            echo "-> Backup VERSION 1 found. Loading backup..."
            echo "$(date) --> Backup VERSION 1 found. Loading backup..." >> $logpath/juggler.log               
            if [ -f ${target}/easyepg_backup.zip ]; then rm -rf ${target}/easyepg_backup.zip; fi
            cp $source/easyepg_backup.ver1 $target/easyepg_backup.zip
            echo "-> VERSION 1 copied..."
            echo "$(date) --> VERSION 1 copied..." >> $logpath/juggler.log 
            (cd /app/easyepg/ && s6-setuidgid app /bin/bash /app/easyepg/restore.sh)
            echo "-> VERSION 1 restored..."
            echo "$(date) --> VERSION 1 restored..." >> $logpath/juggler.log
            rm -rf $target/easyepg_backup.zip
         else
            echo "-> Error - No backup VERSION 1 does exist yet. Run ee bkp now to create a backup."
         fi                                
      ;;
      2)
         if [ -f ${source}/easyepg_backup.ver2 ]; then
            echo "-> Backup VERSION 2 found. Loading backup..."
            echo "$(date) --> Backup VERSION 2 found. Loading backup..." >> $logpath/juggler.log               
            if [ -f ${target}/easyepg_backup.zip ]; then rm -rf ${target}/easyepg_backup.zip; fi
            cp $source/easyepg_backup.ver2 $target/easyepg_backup.zip
            echo "-> VERSION 2 copied..."
            echo "$(date) --> VERSION 2 copied..." >> $logpath/juggler.log 
            (cd /app/easyepg/ && s6-setuidgid app /bin/bash /app/easyepg/restore.sh)
            echo "-> VERSION 2 restored..."
            echo "$(date) --> VERSION 2 restored..." >> $logpath/juggler.log
            rm -rf $target/easyepg_backup.zip
         else
            echo "-> Error - No backup VERSION 3 does exist yet. Run ee bkp now to create a backup."   
         fi   
      ;;
      3)
         if [ -f ${source}/easyepg_backup.ver3 ]; then
            echo "-> Backup VERSION 3 found. Loading backup..."
            echo "$(date) --> Backup VERSION 3 found. Loading backup..." >> $logpath/juggler.log               
            if [ -f ${target}/easyepg_backup.zip ]; then rm -rf ${target}/easyepg_backup.zip; fi
            cp $source/easyepg_backup.ver3 $target/easyepg_backup.zip
            echo "-> VERSION 3 copied..."
            echo "$(date) --> VERSION 3 copied..." >> $logpath/juggler.log 
            (cd /app/easyepg/ && s6-setuidgid app /bin/bash /app/easyepg/restore.sh)
            echo "-> VERSION 3 restored..."
            echo "$(date) --> VERSION 3 restored..." >> $logpath/juggler.log
            rm -rf $target/easyepg_backup.zip
         else
            echo "-> Error - No backup VERSION 3 does exist yet. Run ee bkp now to create a backup."   
         fi   
      ;;
      *)
         echo "-> Error 103 - Please choose a valid option."
         echo "$(date) --> Error 103 - Please choose a valid option." >> $logpath/juggler.log
         echo
      ;;
   esac
else #empty
   echo
   echo "-> Error - No backup location found. Run ee bkp reload or ee bkp reset."
   echo "$(date) --> No backup location found. Run ee bkp reload or ee bkp reset." >> $logpath/juggler.log #/app/data/scripts/load: line 145: /juggler.log: Permission denied
   echo
fi