#!/usr/bin/with-contenv bash

echo 
echo "Checking for log directory"
if [ ! -d /config/logs ]; then
    echo "-> Creating logs dir..."
    mkdir /config/logs
else
    echo "-> ...found."
fi
echo 
echo "Checking for data directory"
if [ ! -d /data ]; then
    echo "-> Creating data dir..."
    mkdir /data
else
    echo "-> ...found."
fi
echo 
echo "Checking for XML link"
if [ ! -d /app/easyepg/xml ]; then
    echo "-> ...not found."
    echo "-> Creating link."
    ln -s /data /app/easyepg/xml
else
    target=/app/easyepg/xml
    if [ "$(find "$target" -mindepth 1 -print -quit 2>/dev/null)" ]; then
        echo "ERROR: XML output traget not empty!"
        echo "Due to safety measures no link has been created."
    else
        rm -rf $target
        echo "-> Creating link..."
        ln -s /data /app/easyepg/xml
    fi
fi
echo
echo "Checking for status directory"
if [ ! -d /config/status ]; then
    echo "-> Creating status dir..."
    mkdir -p /config/status
    echo "Setting default - ENABLED"
    touch /config/status/enabled
else
    echo "-> ...found."
    echo "Checking for status settings"
    if [ -f /config/status/enabled ] && [ ! -f /config/status/disabled ]; then
        echo "-> Service is ENABLED"
    else
        if [ -f /config/status/disabled ] && [ ! -f /config/status/enabled ]; then
        echo "-> Service is DISABLED"
        else
            echo "No Valid Status Setting found."
            echo "Setting default - ENABLED"
            rm -rf /config/status/*
            touch /config/status/enabled
        fi
    fi
fi
echo 
echo "Setting owner, current settings are:"
chown -R app:app /config
chown -R app:app /data
chown -R app:app /tmp
echo
ls -l / | grep app | awk 'NR > 1 { print " -> " $1 " " $3 ":" $4 " /" $9 }'
echo 

printf %s "Done" && printf '%s\n' " OK"